### ISSUE TITLE
Feature request: recursive move

### ISSUE THREAD

**Issue by markomi** [HumanBrainProject/hbp_archive#13]
Hi,
would it be possible to implement a recursive move feature? 

With a recursive move one could for example move a "directory" type object to a new location within a container. Additionally, the recursive move would also transfer all objects from lower levels of the directory's pseudo-hierarchy.

Thanks for considering.

Best,
Milica

**Comment by appukuttan-shailesh** [comment]
I have done some basic testing with these directory level operations and everything seems to be alright. @markomi : Could you test these and let us know if you encounter any issues?

p.s. Since you seem to be a regular user of this tool, you might be interested in #16
