### ISSUE TITLE
Feature request: remove users from ACL

### ISSUE THREAD

**Issue by markomi** [HumanBrainProject/hbp_archive#14]
Hi,
the grant_access() feature of hbp_archive is very handy for giving users access to containers. I was wondering if you would be able to extend the ACL management functionality to allow removal of users from read / write ACLs for any given container?
This would be great to have. Once implemented, superusers would not need to use openstack cli for ACL management at all.

Best,
Milica

**Comment by appukuttan-shailesh** [comment]
@markomi : Thanks for the idea! We have implemented this now. Could you test these and let us know if you encounter any issues?

Also, you can find documentation for the various features here: https://hbp-archive.readthedocs.io
