### ISSUE TITLE
Update handling of exceptions, logs

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp_archive#17]
As discussed in #15 :

> ... we should not be catching Exceptions when they are raised, so the except ... statements and the logger.error calls should be removed.

>  ... perhaps make it easy for the user to get the log messages printed to the screen, for example by adding an argument to the Project and Container constructors

**Comment by appukuttan-shailesh** [comment]
@apdavison : Could you elaborate a bit on the above, I am not sure I entirely follow.
1) Should we just let the exceptions be raised without making any efforts to provide friendly feedback? Such as the input being invalid etc?
2) Is this like having a parameter `logLevel` that sets the log levels (https://docs.python.org/2/library/logging.html#logging-levels)

**Comment by apdavison** [comment]
1. the friendly feedback should all be in the error message: `raise SomeError("friendly message goes here")`
2. I was thinking of something like `log={'screen'|<filename>|None}`
