### ISSUE TITLE
Add feature to create and rename a container

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp_archive#24]
Operator level accounts should be allowed to create and rename containers.

**Comment by appukuttan-shailesh** [comment]
Apparently we cannot rename containers. The reason is explained [here](https://bugs.launchpad.net/swift/+bug/1231540).

Renaming a container, if necessary, would entail copying the contents of the existing container to a new container (with desired name) and then deleting the old container. As this is potentially a 'heavy' task, not sure if we should provide a single convenience function to do everything required (users might be tempted to use it more frequently?).

@apdavison : Also, should we provide a delete container method in this package? Or considering the possible consequences of accidental deletion, should we not include this within the scope of this package?

**Comment by apdavison** [comment]
Probably best not to have a convenience function for rename. Maybe have a `rename()` function, but have it raise a `NotImplementedError` explaining the create/copy/delete process, and a link to the explanation of why direct renaming is not possible?

I think yes for delete, but include a manual step where the user has to type in a phrase like "I confirm I wish to delete the container named xyz", and tell the user how many files they will be deleting.

**Comment by appukuttan-shailesh** [comment]
Closed via #27
